apiVersion: v1
kind: Pod
metadata:
  name: broken
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      command: ["nginx", "-g", "this-will-fail"]  # Intentionally broken command
